### ISSUE TITLE
shadow-cljs: Failed to connect to localhost

### ISSUE THREAD

**Issue by ghost** [jgoodhcg/create-expo-cljs-app#2]
Hi! I've gotten expo working with JS, now I'd like to get it to work with CLJS and your command seems great for that. However I'm getting the below error when running `yarn start` (while running `shadow-cljs watch app` in another terminal). Any ideas? Thanks!

```
Android Running app on moto g(8) plus

Debugger and device times have drifted by more than 60s. Please correct this by running adb shell "date `date +%m%d%H%M%Y.%S`" on your debugger machine.
at node_modules/expo/build/logs/LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

Unable to symbolicate stack trace: The stack is null

The shadow-cljs Websocket was disconnected.
at node_modules/expo/build/logs/LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

shadow-cljs - remote-error, Event {
  "isTrusted": false,
  "message": "Failed to connect to localhost/127.0.0.1:9630",
}
at node_modules/expo/build/logs/LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals
```

**Comment by ghost** [comment]
Also I'm not sure if it's related, but this warning at the start of `yarn start` might be of interest. The CLI let me choose to ignore it.

```
Opening developer tools in the browser...
Project is using deprecated .expo.* file extensions.
Please refactor the following files accordingly:

- /home/marein/projects/yente-cljs/build/shadow.expo.js

Dangerously disable this check with EXPO_LEGACY_IMPORTS=1
Learn more: http://expo.fyi/expo-extension-migration
```

edit: Seems unrelated: https://github.com/thheller/shadow-cljs/issues/917

**Comment by ghost** [comment]
I tried setting up a project from scratch manually but ran into the same error.

**Comment by ghost** [comment]
There seems to be some talk about (un)setting `:local-ip` to fix this issue (e.g. [here](https://githubmemory.com/repo/thheller/shadow-cljs/issues/940)), but it didn't help for me. Possibly I didn't do it correctly.

**Comment by chrisghost** [comment]
I fixed this by opening the debugger tab using my LAN IP : http://192.168.0.1:19000/debugger-ui/

**Comment by ghost** [comment]
You're a hero! I had concluded that the problem was with `shadow-cljs` and created [an issue on that repo](https://github.com/thheller/shadow-cljs/issues/957), but after the creator of `shadow-cljs` and I weren't able to make any progress, I was just about to give up on expo+shadow-cljs.

But, your solution seems to work consistently! Thanks so much!

I will close this issue since there is a workaround and the problem is with `shadow-cljs` anyways. If more discussion is needed, I suggest it happens on the issue I linked above.
